FROM golang:1.11-alpine

ADD . $GOPATH/src/github.com/skycoin/skycoin/
RUN apk add --no-cache gcc musl-dev
RUN apk add git && apk add wget && apk add make && apk add bash && apk add curl
WORKDIR $GOPATH/src/github.com/skycoin/skycoin/ci-scripts/

