FROM golang:1.11-alpine

ADD . $GOPATH/src/github.com/simelo/skycoin/
RUN apk add --no-cache gcc musl-dev
RUN apk add git && apk add wget && apk add make
WORKDIR $GOPATH/src/github.com/simelo/skycoin/ci-scripts/

